create table "public"."urls" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "original" text not null,
    "short_code" character varying,
    "name" text not null
);


alter table "public"."urls" enable row level security;

CREATE UNIQUE INDEX urls_pkey ON public.urls USING btree (id);

CREATE UNIQUE INDEX urls_short_code_key ON public.urls USING btree (short_code);

alter table "public"."urls" add constraint "urls_pkey" PRIMARY KEY using index "urls_pkey";

alter table "public"."urls" add constraint "urls_short_code_key" UNIQUE using index "urls_short_code_key";

grant delete on table "public"."urls" to "anon";

grant insert on table "public"."urls" to "anon";

grant references on table "public"."urls" to "anon";

grant select on table "public"."urls" to "anon";

grant trigger on table "public"."urls" to "anon";

grant truncate on table "public"."urls" to "anon";

grant update on table "public"."urls" to "anon";

grant delete on table "public"."urls" to "authenticated";

grant insert on table "public"."urls" to "authenticated";

grant references on table "public"."urls" to "authenticated";

grant select on table "public"."urls" to "authenticated";

grant trigger on table "public"."urls" to "authenticated";

grant truncate on table "public"."urls" to "authenticated";

grant update on table "public"."urls" to "authenticated";

grant delete on table "public"."urls" to "service_role";

grant insert on table "public"."urls" to "service_role";

grant references on table "public"."urls" to "service_role";

grant select on table "public"."urls" to "service_role";

grant trigger on table "public"."urls" to "service_role";

grant truncate on table "public"."urls" to "service_role";

grant update on table "public"."urls" to "service_role";

create policy "Anyone can do anything"
on "public"."urls"
as permissive
for all
to public
using (true);